services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: utm
      POSTGRES_PASSWORD: utm
      POSTGRES_DB: utm_tracking
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
